name: Publish Binary
on:
  release:
    types:
      - created
jobs:
  binary:
    runs-on: ubuntu-latest
    container:
      image: flanksource/build-tools:0.6
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Binary
        run: make release
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./.bin/build-tools
          asset_name: build-tools
          asset_content_type: application/octet-stream
      - name: Upload MacOSX Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./.bin/build-tools_osx
          asset_name: build-tools_osx
          asset_content_type: application/octet-stream
